[project]
name = "dev-sec-ops-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.0.5",
    "ollama>=0.6.1",
]
